### PR TITLE
fix the issue #148. 

### PR DESCRIPTION
**Pull request by hygkui**
for different env.LANG setting, the verify result will always be in English.

### CODE REVIEW

**Comment by jlord** [comment]
Oh, cool, I didn't know you could do this without doing it for the whole system :sparkles:

**Comment by jlord** [comment]
I'll add a note in the readme that the language will be changed to English in Git-it.

Also this handles #27

**Comment by Silerra** [comment]
LANG=en_US.UTF-8 doesn't work on my PC and I don't know how to install it this lang-pack.
And here:
bildschirmfoto6

So I changed the lang to 'c' in file git-it.js then:
bildschirmfoto7

I hope this info is helpful.

**Comment by Silerra** [comment]
Ah, that also works: LANG=DEFAULT

**Comment by jlord** [comment]
Awesome, it is @Silerra!

**Pull request merged**
