### PR TITLE
Sticky nav css refactor

### PR DESCRIPTION
**Pull request by samjewell**
Hi @jlord Merry Christmas

Have been working on this a couple of weeks back, thought I better get it into a PR or it would never happen.

I'm pleased with these suggestions, but unfortunately I seem to have broken the chinese version - did you know? There isn't a header / footer partial in the chinese version is there? Are you thinking of making a build process for the chinese version as we have for the english version at some point?

Anyway, not sure if I or you might get around to fixing the Chinese version soon, but here's the lowdown on this PR:

Hover is nicer on the link to home:
### from this

oldhome-link
### to this

newhomelink

And the nav is now sticky (well it's stuck fast really):
#### (look at the behaviour of the gif only, colours are broken)

stucknav

Also refactored the CSS quite a bit more. Fairly sure this is what has broken the Chinese pages, as I have refactored some of the HTML to match my changes to the CSS, but haven't updated the Chinese pages to match I don't think (I guess I naively assumed they would copy themselves from the english ones during the build process!)

Thanks - let me know your thoughts :-D

### CODE REVIEW

**Comment by jlord** [comment]
Awesome! Lemme look into the Chinese version before merging, I definitely don't want to break it so I may need to change it so that updates can happen on both.

**Comment by samjewell** [comment]
Yeah sorry - I realise you probs won't merge this in - I'm having a look around the Chinese section now, so hopefully I'll get to that and fix it :-)

**Comment by samjewell** [comment]
So yeah, I think the chinese version is fixed now too. The only differences are ones I intended (I reduced the padding while I was refactoring the CSS, and thought it was fine with less padding)

New version is on the LEFT:
screen shot 2015-01-07 at 23 39 37
screen shot 2015-01-07 at 23 40 56

**Comment by samjewell** [comment]
@jlord heya - I'm pretty sure I fixed the chinese version - all it needed was to be compiled from source again... So fairly sure this is ready to merge. Anything you're still waiting on?

Thanks!

**Comment by jlord** [comment]
Hiya! I really appreciated the contribution, really, really—I'm just waiting on time :grin: I've got a few more projects going that I'd like to wrap up before I dig into this (and other PRs) (plus life), promise I'm not ignoring it! :balloon:

**Comment by samjewell** [comment]
Cool beans :-) 
No worries, I know the feeling - good luck with the projects!

**Comment by jlord** [comment]
I just pulled everything down locally and saw the changes for a second, but then they were gone. Trying to figure out what I did..

**Comment by jlord** [comment]
Ah, wish I had waited one more second before writing that—I'd clicked on a link and was on the live version of the guide an not my local one :stuck_out_tongue: 

It looks great, so excited for this! :sparkles: thanks so much!

**Comment by samjewell** [comment]
@jlord you're welcome, thanks for merging :-D

**Pull request merged**
